name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13
      uses: actions/setup-node@v1
      with:
        node-version: 12.13
    - name: npm install, build, and test
      run: |
        git config --global user.email "joseconstela@users.noreply.github.com"
        git config --global user.name "Jose Constela"
        echo "machine github.com login joseconstela password ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}" > ~/.netrc
        cd website && yarn install && GIT_USER=joseconstela yarn run publish-gh-pages
      env:
        CI: true
